export const clients = [
  { name: "Amazon", logoPath: "/logos/amazon.svg" },
  { name: "Microsoft", logoPath: "/logos/microsoft.png" },
  { name: "Coca-Cola", logoPath: "/logos/coca-cola.svg" },
  { name: "Nike", logoPath: "/logos/nike.svg" },
  { name: "McDonald's", logoPath: "/logos/mcdonalds.svg" },
  { name: "Starbucks", logoPath: "/logos/starbucks.png" },
  { name: "Disney", logoPath: "/logos/disney.svg" },
  { name: "Samsung", logoPath: "/logos/samsung.svg" },
  { name: "Toyota", logoPath: "/logos/toyota.png" },
  { name: "Netflix", logoPath: "/logos/netflix.svg" },
  { name: "Airbnb", logoPath: "/logos/airbnb.svg" },
  { name: "Booking.com", logoPath: "/logos/booking.svg" },
  { name: "Unilever", logoPath: "/logos/unilever.svg" },
  { name: "Visa", logoPath: "/logos/visa.svg" },
  { name: "Tata", logoPath: "/logos/tata.svg" },
  { name: "Mercedes-Benz", logoPath: "/logos/mercedes-benz.svg" },
  { name: "Adidas", logoPath: "/logos/adidas.svg" },
  { name: "L'Oreal", logoPath: "/logos/loreal.svg" },
  { name: "Costco", logoPath: "/logos/costco.svg" },
  { name: "IKEA", logoPath: "/logos/ikea.svg" },
  { name: "Ghana Government", logoPath: "/logos/ghana-coat-of-arms.svg" },
];
